---
general:
  logging_mode: terminal  # Options: <terminal, file, db, test>

framework:
  events: ['gcp_state_changed', 'device_state_changed', 'iot_traffic', 'host_health', 'device_sensor_data', 'digital_twin']

system_components:
  gcp: false
  mqtt_gateway: false
  db: true
  host_monitor: false
  device_manager: true

logging:
  file_log_folder: 'C:\Users\woute\development\logs'
  min_log_level: debug
  log_collection_name: logs

mqtt_gateway:
  broker_address: '127.0.0.1'

mongo_db:
  host_ip: '127.0.0.1'
