---
general:
  logging_mode: db  # Options: <terminal, file, db, test>

system_components:
  mqtt_gateway: true
  db: true
  host_monitor: true

logging:
  file_log_folder: 'C:\Users\woute\development\logs'
  min_log_level: info
  log_collection_name: logs

mqtt_gateway:
  broker_address: 'mqtt_mosquitto_broker'

mongo_db:
  host_ip: 'mongo'
